import Chat from "@/components/chat";
import ConversationList from "@/components/chat/ConversationList";
import { MobileConversationList } from "@/components/chat/MobileConversationList";
import { Header } from "@/components/layout/Header";
import { MobileMenu } from "@/components/layout/MobileMenu";
import { ChatProvider } from "@/contexts/chat.context";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-screen h-screen">
        <div className="fixed w-full">
          <Header />
        </div>
        <ChatProvider>
          <div className="flex flex-1 pt-12 max-w-full h-full">
            <div className="border-r hidden lg:block lg:w-1/5 px-2">
              <ConversationList />
            </div>
            <MobileConversationList />
            <div className="max-w-full w-full">
              <Chat />
            </div>
          </div>
        </ChatProvider>
      </main>
    </>
  );
}
